@ForumApi_HostAddress = https://web-app-forum-a6excaf5gzaxb4aj.northeurope-01.azurewebsites.net
@tenantId = df9168f1-9785-4389-a6ea-e30c48a1e65d
@clientId = 262ce4e8-cefb-4794-b1b8-ce688858150a
@clientSecret = REPLACE_WITH_YOUR_CLIENT_SECRET

# @name autentikointi
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&client_secret={{clientSecret}}&scope=api://{{clientId}}/.default&grant_type=client_credentials

###
GET {{ForumApi_HostAddress}}/api/topics
Accept: application/json

###
POST {{ForumApi_HostAddress}}/api/topics
Content-Type: application/json
{
  "title": "Sports"
}