@ForumApi_HostAddress = http://localhost:5256

GET {{ForumApi_HostAddress}}/api/topics
Accept: application/json

###

POST {{ForumApi_HostAddress}}/api/topics
Content-Type: application/json

{
  "title": "Sports"
}

###
PUT {{ForumApi_HostAddress}}/api/topics/1
Content-Type: application/json

{
  "title": "Movies"
}

###

DELETE {{ForumApi_HostAddress}}/api/topics/1

###
POST {{ForumApi_HostAddress}}/api/topics/2/messages
Content-Type: application/json

{
  "content": "I love movies",
  "userId": "anonymous"
}

###
GET {{ForumApi_HostAddress}}/api/topics/1003/messages
Accept: application/json
